version: '3.8'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: visagov_prueba
    container_name: visagov_prueba
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 

volumes:
  db_data: {}
